# Generated by Django 6.0.3 on 2026-04-08 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("url_pagina_lusofona", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
            ],
            options={
                "verbose_name_plural": "Docentes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(max_length=20)),
                ("instituicao", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("ano_inicio", models.IntegerField()),
                ("ano_fim", models.IntegerField(blank=True, null=True)),
                ("url_curso", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Licenciaturas",
            },
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entidade",
                    models.CharField(
                        choices=[
                            ("licenciatura", "Licenciatura"),
                            ("uc", "Unidade Curricular"),
                            ("docente", "Docente"),
                            ("projeto", "Projeto"),
                            ("tecnologia", "Tecnologia"),
                            ("tfc", "TFC"),
                            ("competencia", "Competência"),
                            ("formacao", "Formação"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("data", models.DateField(auto_now_add=True)),
                ("descricao_decisoes", models.TextField()),
                ("erros_encontrados", models.TextField(blank=True)),
                ("correcoes", models.TextField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
            ],
            options={
                "verbose_name": "Making Of",
                "verbose_name_plural": "Making Of",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("categoria", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("url", models.URLField(blank=True)),
                ("interesse", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Tecnologias",
            },
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("tipo", models.CharField(max_length=50)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "certificado",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.tecnologia"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Formações",
            },
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("nivel", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias",
                        to="portfolio.tecnologia",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Competências",
            },
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("autor", models.CharField(blank=True, max_length=200)),
                ("curso", models.CharField(blank=True, max_length=200)),
                ("resumo", models.TextField(blank=True)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Sem Interesse"),
                            (2, "Pouco Interessante"),
                            (3, "Interessante"),
                            (4, "Muito Interessante"),
                            (5, "Perfeito"),
                        ],
                        null=True,
                    ),
                ),
                ("orientador", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "palavras_chave",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("areas", models.CharField(blank=True, max_length=300, null=True)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="tfcs/")),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfcs",
                        to="portfolio.licenciatura",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "TFCs",
            },
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=20)),
                ("ano_curricular", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("avaliacao", models.TextField(blank=True)),
                ("ects", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True, related_name="ucs", to="portfolio.docente"
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Unidades Curriculares",
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField(blank=True)),
                ("url_github", models.URLField(blank=True)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("video", models.URLField(blank=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projetos",
            },
        ),
    ]
