# Generated by Django 6.0.3 on 2026-03-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(max_length=20)),
                (
                    "instituicao",
                    models.CharField(default="Universidade Lusófona", max_length=200),
                ),
                ("descricao", models.TextField(blank=True)),
                ("ano_inicio", models.IntegerField()),
                ("ano_fim", models.IntegerField(blank=True, null=True)),
                ("url_curso", models.URLField(blank=True)),
                ("grau", models.CharField(default="Licenciatura", max_length=50)),
            ],
            options={
                "verbose_name_plural": "Licenciaturas",
            },
        ),
    ]
