# Generated by Django 6.0.3 on 2026-03-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("url_pagina_lusofona", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Docentes",
                "ordering": ["nome"],
            },
        ),
    ]
