# Generated by Django 6.0.3 on 2026-03-29 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_docente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("linguagem", "Linguagem de Programação"),
                            ("framework", "Framework / Biblioteca"),
                            ("bd", "Base de Dados"),
                            ("devops", "DevOps / Ferramentas"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("url_oficial", models.URLField(blank=True)),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        choices=[
                            (1, "⭐ Básico"),
                            (2, "⭐⭐ Intermédio"),
                            (3, "⭐⭐⭐ Avançado"),
                        ],
                        default=1,
                    ),
                ),
                ("destaque", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Tecnologias",
                "ordering": ["-nivel_interesse", "nome"],
            },
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=20)),
                ("ano_curricular", models.IntegerField()),
                (
                    "semestre",
                    models.IntegerField(
                        choices=[(1, "1.º Semestre"), (2, "2.º Semestre")]
                    ),
                ),
                ("ects", models.IntegerField(default=6)),
                ("descricao", models.TextField(blank=True)),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True, related_name="ucs", to="portfolio.docente"
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade Curricular",
                "verbose_name_plural": "Unidades Curriculares",
                "ordering": ["ano_curricular", "semestre", "nome"],
            },
        ),
    ]
