# Generated by Django 6.0.3 on 2026-04-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_unidadecurricular_bibliografia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="avaliacao",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="foto",
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="codigo_curso",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="codigo_uc",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
