# Generated by Django 6.0.3 on 2026-03-29 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_tecnologia_unidadecurricular"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField(blank=True)),
                ("url_github", models.URLField(blank=True)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projetos",
                "ordering": ["-data_fim"],
            },
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tecnica", "Técnica"),
                            ("soft", "Soft Skill"),
                            ("linguistica", "Linguística"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nivel",
                    models.IntegerField(
                        choices=[
                            (1, "Básico"),
                            (2, "Intermédio"),
                            (3, "Avançado"),
                            (4, "Especialista"),
                        ],
                        default=1,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias",
                        to="portfolio.tecnologia",
                    ),
                ),
                (
                    "projetos",
                    models.ManyToManyField(
                        blank=True, related_name="competencias", to="portfolio.projeto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Competência",
                "verbose_name_plural": "Competências",
                "ordering": ["tipo", "-nivel"],
            },
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("autor", models.CharField(blank=True, max_length=200)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField(blank=True)),
                ("url_repositorio", models.URLField(blank=True)),
                ("url_documento", models.URLField(blank=True)),
                (
                    "interesse",
                    models.IntegerField(
                        choices=[(1, "Baixo"), (2, "Médio"), (3, "Alto")], default=1
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
            options={
                "verbose_name": "TFC",
                "verbose_name_plural": "TFCs",
                "ordering": ["-interesse", "-ano"],
            },
        ),
    ]
