# Generated by Django 6.0.3 on 2026-04-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_remove_unidadecurricular_avaliacao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unidadecurricular",
            old_name="descricao",
            new_name="apresentacao",
        ),
    ]
