# Generated by Django 6.0.3 on 2026-03-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_projeto_competencia_tfc"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entidade",
                    models.CharField(
                        choices=[
                            ("licenciatura", "Licenciatura"),
                            ("uc", "Unidade Curricular"),
                            ("docente", "Docente"),
                            ("projeto", "Projeto"),
                            ("tecnologia", "Tecnologia"),
                            ("tfc", "TFC"),
                            ("competencia", "Competência"),
                            ("formacao", "Formação"),
                            ("makingof", "MakingOf"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("data", models.DateField(auto_now_add=True)),
                ("descricao_decisoes", models.TextField()),
                ("erros_encontrados", models.TextField(blank=True)),
                ("correcoes", models.TextField(blank=True)),
                ("uso_ia", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Making Of",
                "verbose_name_plural": "Making Of",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("curso", "Curso Online"),
                            ("certificacao", "Certificação"),
                            ("workshop", "Workshop"),
                            ("academico", "Percurso Académico"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_conclusao", models.DateField(blank=True, null=True)),
                (
                    "certificado",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.tecnologia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Formação",
                "verbose_name_plural": "Formações",
                "ordering": ["-data_conclusao"],
            },
        ),
    ]
