# Generated by Django 6.0.3 on 2026-03-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_makingof_formacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="docente",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="docentes/"),
        ),
        migrations.AddField(
            model_name="makingof",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="makingof/"),
        ),
        migrations.AddField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="projetos/"),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
        ),
    ]
