# Generated by Django 6.0.3 on 2026-04-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_remove_tfc_orientador_tfc_orientador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
