# Generated by Django 6.0.5 on 2026-05-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_projeto_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='nome',
            field=models.CharField(max_length=500),
        ),
    ]
