# Generated by Django 6.0.5 on 2026-05-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_docente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='nome',
            field=models.TextField(),
        ),
    ]
