# Generated by Django 6.0.5 on 2026-05-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_docente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatura',
            name='instituicao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='nome',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='makingof',
            name='titulo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='autor',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='curso',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='palavras_chave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='titulo',
            field=models.TextField(),
        ),
    ]
